### ISSUE TITLE
sgc error when running rainbow for a second time

### ISSUE THREAD

**Issue by markmellors** [markmellors/Piradigm#119]
in branch rainbow learning, after a successful run and the screen is back on teh mnu, selected rainbow gives the following error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/Piradigm/rainbow.py", line 506, in run
    sgc.update(time)
  File "/home/pi/Piradigm/sgc/widgets/_locals.py", line 126, in update
    _fade(widget)
  File "/home/pi/Piradigm/sgc/widgets/_locals.py", line 50, in _fade
    widget._fade -= time / 4.
TypeError: unsupported operand type(s) for /: 'module' and 'float'

challenge finished
This doesn't happen on master.

**Comment by robberwick** [comment]
that error would indicate that `time` has been overwritten by a reference to a module called `time`. so, anywhere that `import time` is used, consider using `import time as time_module` or similar to prevent such namespace clashes. Note that `time.sleep()` would need to be `time_module.sleep()` thereafter.

**Comment by robberwick** [comment]
rainbow.py line 506  calls `sgc.update(time)`, where `time` is a reference to the `time` module, not an integer value. Do you mean `time.time()`?

**Comment by markmellors** [comment]
time was getting overwritten in menu:
`time = clock.tick(30)
sgc.update(time)`
changed that to timer, working now.

**Comment by robberwick** [comment]
Assigning back to @markmellors to implement https://github.com/markmellors/Piradigm/issues/119#issuecomment-382032783.

**Comment by robberwick** [comment]
that error still exists in rainbow.py - a module reference is being passed insteda of an integer value. this should also be fixed as it is a source of bugs.

**Comment by markmellors** [comment]
error fixed in rainbow too
