### ISSUE TITLE
logging not visible on a single ssh connection

### ISSUE THREAD

**Issue by markmellors** [markmellors/Piradigm#16]
would be good to allow console logging and file logging for debugging purposes

**Comment by markmellors** [comment]
fixed, now using & tail -F ... on same line, or using a separate terminal

**Comment by robberwick** [comment]
I think this is still a worthwhile upgrade, although not a blocking issue.

**Comment by robberwick** [comment]
Labelling as an enhancement and yoinking onto my queue

**Comment by markmellors** [comment]
addressed by commit 176afc1acd6a36609ace95cbd70e07814ef4a415
