### ISSUE TITLE
Add a gitignore and clean up unwanted files from the index

### ISSUE THREAD

**Issue by robberwick** [markmellors/Piradigm#19]
There are some files we don't want tracked in version control e.g.:
* sublime project and workspace files
* compiled python (`*.pyc`) files
* log files

We should look to remove those from the index and create a `.gitignore` file to prevent them from being included in the future.

**Comment by markmellors** [comment]
Does the log show the missing log messages issue?

**Comment by robberwick** [comment]
I didn't check it for missing lines. If that's something you need to do, I'd suggest backing your log file first. Adding it to the gitignore just means that when you come to do a `git add .` you won't commit the log file.

**Comment by markmellors** [comment]
I thought having the log file would be useful for either of us debugging away from the pi

**Comment by robberwick** [comment]
But my log would always be different to your log, and contain all the logging ever done, so they would clash. also, switching branches would also switch log files (because they'd be versioned). Better to copy any logs of interest and deal with them outside of version control.

Which reminds me, I was going to set the log to be rotating so it didn't just keep getting bigger until it ate the whole disk..

**Comment by markmellors** [comment]
fixed for master on commit 11d1dd0fc25cc1f78aba7c38c095fec5ffe78a7c
