### ISSUE TITLE
logging issue stops menu.py from launching from buttonwatcher.py

### ISSUE THREAD

**Issue by markmellors** [markmellors/Piradigm#71]
Log details:
Dec 17 18:21:18 Piradigm ntpd[572]: peers refreshed
Dec 17 18:21:19 Piradigm python[589]: Traceback (most recent call last):
Dec 17 18:21:19 Piradigm python[589]: File "/home/pi/Piradigm/menu.py", line 39, in <module>
Dec 17 18:21:19 Piradigm python[589]: logging.config.fileConfig('logging.ini')
Dec 17 18:21:19 Piradigm python[589]: File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
Dec 17 18:21:19 Piradigm python[589]: formatters = _create_formatters(cp)
Dec 17 18:21:19 Piradigm python[589]: File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
Dec 17 18:21:19 Piradigm python[589]: flist = cp.get("formatters", "keys")
Dec 17 18:21:19 Piradigm python[589]: File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
Dec 17 18:21:19 Piradigm python[589]: raise NoSectionError(section)Dec 17 18:21:19 Piradigm python[589]: ConfigParser.NoSectionError: No section: 'formatters'
Dec 17 18:21:19 Piradigm sudo[747]: pam_unix(sudo:session): session closed for user root

**Comment by robberwick** [comment]
Fixed by https://github.com/markmellors/Piradigm/commit/f083a9145e60fe3eb9d75b88bd277f9d49d8e761
