### ISSUE TITLE
aruco makes new markers every time its run - so maze and speed challenge can't run twice

### ISSUE THREAD

**Issue by markmellors** [markmellors/Piradigm#86]
fix could be either changing dictionary scope so aruco object is recreated every time challenge starts, or only once per session, or load a pre-made dictionary.

**Comment by robberwick** [comment]
I think we might need to use `cPickle` or `dill` in order to serialise our dictionary to disc and then load and deserialise for each run.

**Comment by markmellors** [comment]
there's a C example here of how to save a dictionary: https://stackoverflow.com/questions/35293750/opencv-3-and-aruco-lib-serialize-dictionary

This page suggests the issue comes directly from the random number seed, so the shady hack would be to reset that: https://github.com/opencv/opencv_contrib/issues/1457

**Comment by markmellors** [comment]
fixed with commit f24fce62177fb03530365e148b4533fa495c8014
